package("lvgl")
    add_deps("cmake")
    set_sourcedir(path.join(os.scriptdir(), "lvgl-8.3.1"))
    set_policy("package.install_always", true)
    on_install(function (package)
        os.cp("lv_conf_template.h", "src/lv_conf.h")
        local configs = {}
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        import("package.tools.cmake").install(package, configs)
    end)
    on_test(function (package)
        assert(package:has_cfuncs("lv_version_info", {includes = "lvgl/lvgl.h"}))
    end)
package_end()